"""Shared error-response contract per PRD §7.

Every error returns a dict with:
  - context: echoed back from input
  - error: one of the codes below
  - (optional) candidates, hint, suggestions, valid_contexts

Error responses are constructed only via the helpers below so the §7 shape
stays identical everywhere. No tool assembles error dicts ad hoc.
"""

from __future__ import annotations

# Re-export everything from submodules so existing import sites need zero changes.
from .core import (
    ERROR_ACCESS_DENIED,
    ERROR_AMBIGUOUS_RESOURCE,
    ERROR_AUTHENTICATION_FAILED,
    ERROR_DISCOVERY_FAILURE,
    ERROR_EXEC_FAILED,
    ERROR_INVALID_DRY_RUN,
    ERROR_INVALID_GREP_PATTERN,
    ERROR_INVALID_JSONPATH_TEMPLATE,
    ERROR_INVALID_MANIFEST,
    ERROR_INVALID_OUTPUT,
    ERROR_INVALID_PATCH_TYPE,
    ERROR_INVALID_SELECTOR,
    ERROR_KUBECTL_EXEC_ERROR,
    ERROR_KUBECTL_FAILURE,
    ERROR_KUBECTL_INVALID_ARGUMENT,
    ERROR_KUBECTL_NOT_INSTALLED,
    ERROR_KUBECTL_TIMEOUT,
    ERROR_KUBECTL_UNREACHABLE,
    ERROR_NAMESPACE_INVALID,
    ERROR_OBJECT_INVALID,
    ERROR_OBJECT_NOT_FOUND,
    ERROR_UNEXPECTED_OUTPUT,
    ERROR_UNKNOWN_CONTEXT,
    ERROR_UNKNOWN_RESOURCE,
    ERROR_VERB_UNSUPPORTED,
    _base,
    access_denied,
    ambiguous_resource,
    authentication_failed,
    discovery_failure,
    exec_failed,
    invalid_dry_run,
    invalid_grep_pattern,
    invalid_jsonpath_template,
    invalid_manifest,
    invalid_output,
    invalid_patch_type,
    invalid_selector,
    kubectl_access_denied,
    kubectl_ambiguous_resource,
    kubectl_exec_error,
    kubectl_failure,
    kubectl_invalid_argument,
    kubectl_not_installed,
    kubectl_timeout,
    kubectl_unreachable,
    namespace_invalid,
    object_invalid,
    object_not_found,
    unexpected_output,
    unknown_context,
    unknown_resource,
    verb_unsupported,
)
from .files import (
    ERROR_FILE_EXISTS,
    ERROR_FILE_READ_FAILED,
    ERROR_FILE_WRITE_FAILED,
    ERROR_UNSAFE_PATH,
    file_exists,
    file_read_failed,
    file_write_failed,
    unsafe_path,
)
from .helm import (
    ERROR_HELM_RELEASE_DECODE_FAILED,
    ERROR_HELM_RELEASE_NOT_FOUND,
    helm_release_decode_failed,
    helm_release_not_found,
)

__all__ = [
    # Core error codes
    "ERROR_AMBIGUOUS_RESOURCE",
    "ERROR_UNKNOWN_RESOURCE",
    "ERROR_VERB_UNSUPPORTED",
    "ERROR_NAMESPACE_INVALID",
    "ERROR_UNKNOWN_CONTEXT",
    "ERROR_ACCESS_DENIED",
    "ERROR_KUBECTL_FAILURE",
    "ERROR_EXEC_FAILED",
    "ERROR_INVALID_MANIFEST",
    "ERROR_INVALID_OUTPUT",
    "ERROR_INVALID_PATCH_TYPE",
    "ERROR_INVALID_DRY_RUN",
    "ERROR_INVALID_SELECTOR",
    "ERROR_DISCOVERY_FAILURE",
    "ERROR_INVALID_JSONPATH_TEMPLATE",
    "ERROR_INVALID_GREP_PATTERN",
    "ERROR_OBJECT_NOT_FOUND",
    "ERROR_KUBECTL_TIMEOUT",
    "ERROR_KUBECTL_NOT_INSTALLED",
    "ERROR_KUBECTL_EXEC_ERROR",
    "ERROR_KUBECTL_UNREACHABLE",
    "ERROR_AUTHENTICATION_FAILED",
    "ERROR_KUBECTL_INVALID_ARGUMENT",
    "ERROR_OBJECT_INVALID",
    "ERROR_UNEXPECTED_OUTPUT",
    # File-I/O error codes
    "ERROR_UNSAFE_PATH",
    "ERROR_FILE_EXISTS",
    "ERROR_FILE_WRITE_FAILED",
    "ERROR_FILE_READ_FAILED",
    # Helm error codes
    "ERROR_HELM_RELEASE_NOT_FOUND",
    "ERROR_HELM_RELEASE_DECODE_FAILED",
    # Core helpers
    "_base",
    "access_denied",
    "ambiguous_resource",
    "discovery_failure",
    "exec_failed",
    "invalid_grep_pattern",
    "invalid_jsonpath_template",
    "invalid_manifest",
    "invalid_output",
    "invalid_patch_type",
    "invalid_dry_run",
    "invalid_selector",
    "kubectl_failure",
    "kubectl_timeout",
    "kubectl_not_installed",
    "kubectl_exec_error",
    "kubectl_unreachable",
    "kubectl_access_denied",
    "kubectl_ambiguous_resource",
    "authentication_failed",
    "kubectl_invalid_argument",
    "object_invalid",
    "namespace_invalid",
    "object_not_found",
    "unexpected_output",
    "unknown_context",
    "unknown_resource",
    "verb_unsupported",
    # File-I/O helpers
    "file_exists",
    "file_read_failed",
    "file_write_failed",
    "unsafe_path",
    # Helm helpers
    "helm_release_decode_failed",
    "helm_release_not_found",
]
